format = """
[](fg:black)\
$username\
[](bg:yellow fg:black)\
$directory\
[](fg:yellow bg:green)\
$git_branch\
[](fg:green bg:cyan)\
$cmd_duration\
[](fg:cyan)\
$line_break\
$character"""

[username]
show_always = true
style_user = "bg:black fg:white"
format = "[$user]($style)"

[directory]
style = "bg:yellow fg:black"
format = "[ $path ]($style)"
truncation_length = 3

[git_branch]
symbol = " "
style = "bg:green fg:black"
format = "[ $symbol$branch ]($style)"

[cmd_duration]
style = "bg:cyan fg:black"
format = "[  $duration ]($style)"

[line_break]
disabled = false

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
